/**
 * write_new_bot6.js
 * tg_status_bot.js v14 를 처음부터 새로 작성
 *
 * 변경사항:
 * - 어드민: HTTP 방식 포기 → Puppeteer로 로그인 (쿠키 없음 문제 해결)
 * - 단일 browser 인스턴스, admin/곳간 각각 page 분리
 * - tgSend: 재시도 3회 (2초 간격)
 * - 곳간: split('/') 파싱 유지
 * - 정규식 백슬래시 오염 없음 (평문 문자열로 처리)
 * - 명령어: /주문건확인, /주문출력, /승인상태, /명령어리스트
 */

const fs   = require('fs');
const path = require('path');

const TARGET = path.join(__dirname, 'tg_status_bot.js');
const bak    = TARGET.replace('.js', '.v13bak_' + Date.now() + '.js');
fs.copyFileSync(TARGET, bak);
console.log('백업: ' + path.basename(bak));

/* ─────────────────────────────────────────────
   파일에 쓸 코드를 배열로 조립 (이스케이프 오염 방지)
   ───────────────────────────────────────────── */
const lines = [];
function w(s) { lines.push(s); }

w('/**');
w(' * tg_status_bot.js v14');
w(' * 명령어: /주문건확인  /주문출력  /승인상태  /명령어리스트');
w(' * - 어드민: Puppeteer 로그인');
w(' * - tgSend: 재시도 3회');
w(' * - 곳간:   split("/") 파싱');
w(' */');
w("require('dotenv').config({ path: require('path').join(__dirname, '.env') });");
w("const https     = require('https');");
w("const puppeteer = require('puppeteer');");
w('');
w("const TG_TOKEN    = process.env.TG_TOKEN || '8796752509:AAFX54QxpY0SCXxAwpOXqqxVrKEvlZhSNKc';");
w("const TG_CHAT     = process.env.TG_CHAT  || '6097520392';");
w("const ADMIN_HOST  = 'dongnaegotgan.adminplus.co.kr';");
w("const ADMIN_URL   = 'https://' + ADMIN_HOST + '/admin/';");
w("const ADMIN_LOGIN = 'https://' + ADMIN_HOST + '/admin/login.html';");
w("const ADMIN_ID    = process.env.ADMIN_ID || 'dongnaegotgan';");
w("const ADMIN_PW    = process.env.ADMIN_PW || 'rhtrks12!@';");
w("const FG_BASE     = 'https://dongnaegotgan.flexgate.co.kr';");
w("const FG_LOGIN    = 'https://intro.flexgate.co.kr/Mypage/Login';");
w("const FG_ID       = process.env.FG_ID || 'dongnaegotgan';");
w("const FG_PW       = process.env.FG_PW || 'rhtrks12!@';");
w('');
w("function log(m) { console.log('[' + new Date().toLocaleTimeString('ko-KR') + '] ' + m); }");
w('function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }');
w('');

/* ── tgSend 재시도 3회 ── */
w('// ── tgSend 재시도 3회 ───────────────────────────────────────────');
w('async function tgSend(msg, chatId, retry) {');
w("  chatId = chatId || TG_CHAT;");
w('  retry  = (retry === undefined) ? 3 : retry;');
w('  var body = JSON.stringify({ chat_id: chatId, text: msg, parse_mode: "HTML" });');
w('  for (var i = 0; i < retry; i++) {');
w('    try {');
w('      await new Promise(function(resolve, reject) {');
w('        var req = https.request({');
w("          hostname: 'api.telegram.org',");
w("          path: '/bot' + TG_TOKEN + '/sendMessage',");
w("          method: 'POST',");
w("          headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) }");
w('        }, function(res) {');
w("          var d = ''; res.on('data', function(c){ d += c; }); res.on('end', function(){ resolve(d); });");
w('        });');
w('        req.on("error", reject);');
w('        req.write(body); req.end();');
w('      });');
w('      return;');
w('    } catch(e) {');
w("      log('tgSend 오류 (' + (i+1) + '/' + retry + '): ' + e.message);");
w('      if (i < retry - 1) await sleep(2000);');
w('    }');
w('  }');
w('}');
w('');

/* ── tgGetUpdates ── */
w('async function tgGetUpdates(offset) {');
w('  return new Promise(function(resolve) {');
w('    var req = https.request({');
w("      hostname: 'api.telegram.org',");
w("      path: '/bot' + TG_TOKEN + '/getUpdates?offset=' + offset + '&timeout=20&limit=10',");
w("      method: 'GET'");
w('    }, function(res) {');
w("      var d = ''; res.on('data', function(c){ d += c; });");
w('      res.on("end", function() {');
w('        try { var j = JSON.parse(d); resolve(j.ok ? j.result : []); }');
w('        catch(e) { resolve([]); }');
w('      });');
w('    });');
w('    req.on("error", function(){ resolve([]); });');
w('    req.end();');
w('  });');
w('}');
w('');

/* ── 공유 브라우저 ── */
w('// ── 공유 브라우저 ───────────────────────────────────────────────');
w('var browser = null;');
w('');
w('async function getBrowser() {');
w('  if (browser && browser.isConnected()) return browser;');
w("  log('브라우저 시작...');");
w('  browser = await puppeteer.launch({');
w('    headless: true,');
w("    args: ['--no-sandbox','--disable-setuid-sandbox','--lang=ko-KR',");
w("           '--disable-blink-features=AutomationControlled'],");
w('    defaultViewport: { width: 1440, height: 900 },');
w('    ignoreHTTPSErrors: true');
w('  });');
w('  return browser;');
w('}');
w('');

/* ── 어드민 Puppeteer 로그인 ── */
w('// ── 어드민 Puppeteer ────────────────────────────────────────────');
w('var adminPage = null, adminLoginTime = 0;');
w('');
w('async function adminLogin() {');
w('  var b = await getBrowser();');
w('  if (!adminPage || adminPage.isClosed()) {');
w('    adminPage = await b.newPage();');
w('    adminPage.on("dialog", function(d){ d.accept().catch(function(){}); });');
w('    await adminPage.evaluateOnNewDocument(function() {');
w('      Object.defineProperty(navigator, "webdriver", { get: function(){ return false; } });');
w('    });');
w("    await adminPage.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');");
w('  }');
w("  log('  [어드민] 로그인 시작...');");
w('  await adminPage.goto(ADMIN_LOGIN, { waitUntil: "networkidle2", timeout: 20000 });');
w('  await sleep(500);');
w('');
w('  // 폼 필드 탐색 (id/pw 또는 userId/password)');
w("  var idSelectors = ['input[name=\"id\"]','input[name=\"userId\"]','#id','#userId'];");
w("  var pwSelectors = ['input[name=\"pw\"]','input[name=\"password\"]','#pw','#password'];");
w('  var idEl = null, pwEl = null;');
w('  for (var si = 0; si < idSelectors.length; si++) {');
w('    idEl = await adminPage.$(idSelectors[si]).catch(function(){ return null; });');
w('    if (idEl) break;');
w('  }');
w('  for (var si2 = 0; si2 < pwSelectors.length; si2++) {');
w('    pwEl = await adminPage.$(pwSelectors[si2]).catch(function(){ return null; });');
w('    if (pwEl) break;');
w('  }');
w('');
w('  if (!idEl || !pwEl) {');
w('    var inputs = await adminPage.evaluate(function() {');
w('      return Array.from(document.querySelectorAll("input")).map(function(i){ return i.name+"/"+i.type; });');
w('    });');
w("    log('  [어드민] 폼 필드 못찾음: ' + JSON.stringify(inputs));");
w('    return false;');
w('  }');
w('');
w('  await idEl.click({ clickCount: 3 }); await adminPage.keyboard.type(ADMIN_ID);');
w('  await pwEl.click({ clickCount: 3 }); await adminPage.keyboard.type(ADMIN_PW);');
w('  await sleep(300);');
w('');
w("  var loginBtn = await adminPage.$('button[type=\"submit\"],input[type=\"submit\"],.btn-login').catch(function(){ return null; });");
w('  if (loginBtn) {');
w('    await Promise.all([');
w('      adminPage.waitForNavigation({ waitUntil: "networkidle2", timeout: 15000 }).catch(function(){}),');
w('      loginBtn.click()');
w('    ]);');
w('  } else {');
w('    await Promise.all([');
w('      adminPage.waitForNavigation({ waitUntil: "networkidle2", timeout: 15000 }).catch(function(){}),');
w('      pwEl.press("Enter")');
w('    ]);');
w('  }');
w('');
w('  for (var wi = 0; wi < 5; wi++) {');
w('    await sleep(1000);');
w('    var u = adminPage.url();');
w('    if (u.indexOf("login") === -1 && u.indexOf("Login") === -1) break;');
w('  }');
w('');
w("  var afterUrl = adminPage.url();");
w("  log('  [어드민] 로그인 후 URL: ' + afterUrl);");
w('  if (afterUrl.indexOf("login") !== -1 || afterUrl.indexOf("Login") !== -1) {');
w("    log('  [어드민] 로그인 실패');");
w('    return false;');
w('  }');
w('  adminLoginTime = Date.now();');
w("  log('  [어드민] 로그인 성공!');");
w('  return true;');
w('}');
w('');
w('async function ensureAdmin() {');
w('  if (Date.now() - adminLoginTime < 20*60*1000 && adminPage && !adminPage.isClosed()) return true;');
w('  return await adminLogin();');
w('}');
w('');

/* ── getAdminOrders ── */
w('async function getAdminOrders() {');
w('  var ok = await ensureAdmin();');
w('  if (!ok) return { orderCount: 0, prodMap: {}, totalAmount: 0 };');
w('');
w('  var orderCount = 0, prodMap = {}, totalAmount = 0;');
w('  try {');
w('    // stats (신규주문 건수)');
w('    var statsData = await adminPage.evaluate(async function(baseUrl) {');
w('      try {');
w('        var r = await fetch(baseUrl + "xml/real.stats.json.php", {');
w('          method: "POST",');
w('          headers: { "Content-Type": "application/x-www-form-urlencoded", "X-Requested-With": "XMLHttpRequest" },');
w('          body: ""');
w('        });');
w('        return await r.json();');
w('      } catch(e) { return null; }');
w('    }, ADMIN_URL);');
w('');
w('    if (statsData && statsData.spnNew5) {');
w('      orderCount = parseInt(statsData.spnNew5) || 0;');
w("      log('  [어드민 stats] 신규=' + statsData.spnNew5 + ', 오늘=' + statsData.spnNew8);");
w('    }');
w('');
w('    // 주문 목록 JSON API (로그인된 브라우저 컨텍스트에서 호출)');
w('    var todayKST = new Date(Date.now() + 9*60*60*1000).toISOString().slice(0,10);');
w('    var sdateVal = JSON.stringify({ start: todayKST, end: todayKST });');
w('    var qp = "proc=json&mod=order&actpage=od.list.bd"');
w('           + "&status=10&datefld=b.regdate"');
w('           + "&sdate=" + encodeURIComponent(sdateVal)');
w('           + "&bizgrp=all&searchtype=all&searchval="');
w('           + "&_search=false&rows=500&page=1&sidx=regdate&sord=desc";');
w('');
w('    var listData = await adminPage.evaluate(async function(baseUrl, qs) {');
w('      try {');
w('        var r = await fetch(baseUrl + "order/json/od.list.bd.php?" + qs, {');
w('          method: "GET",');
w('          headers: { "X-Requested-With": "XMLHttpRequest" }');
w('        });');
w('        var txt = await r.text();');
w("        // 로그인 페이지로 리다이렉트된 경우");
w('        if (txt.indexOf("userId") !== -1 || txt.indexOf("login") !== -1) {');
w('          return { __loginRequired: true };');
w('        }');
w('        return JSON.parse(txt);');
w('      } catch(e) { return { __error: e.message, rows: [] }; }');
w('    }, ADMIN_URL, qp);');
w('');
w('    if (listData && listData.__loginRequired) {');
w("      log('  [어드민] 세션 만료 → 재로그인');");
w('      adminLoginTime = 0;');
w('      var reOk = await adminLogin();');
w('      if (!reOk) return { orderCount: orderCount, prodMap: prodMap, totalAmount: totalAmount };');
w('      // 재시도');
w('      listData = await adminPage.evaluate(async function(baseUrl, qs) {');
w('        try {');
w('          var r = await fetch(baseUrl + "order/json/od.list.bd.php?" + qs, {');
w('            method: "GET",');
w('            headers: { "X-Requested-With": "XMLHttpRequest" }');
w('          });');
w('          return JSON.parse(await r.text());');
w('        } catch(e) { return { rows: [] }; }');
w('      }, ADMIN_URL, qp);');
w('    }');
w('');
w('    if (listData && listData.__error) {');
w("      log('  [어드민 목록 오류] ' + listData.__error);");
w('    }');
w('');
w('    var rows = (listData && listData.rows) ? listData.rows : [];');
w('    var records = parseInt((listData && listData.records) || rows.length) || 0;');
w("    log('  [어드민] rows=' + rows.length + ', records=' + records);");
w('    if (!orderCount) orderCount = records;');
w('');
w('    rows.forEach(function(row, ri) {');
w('      var cell = Array.isArray(row.cell) ? row.cell : [];');
w("      if (ri === 0) log('  [어드민 cell샘플] ' + JSON.stringify(cell).slice(0,150));");
w('');
w('      // 금액 파싱');
w('      var rowAmt = 0;');
w('      cell.forEach(function(c) {');
w('        if (typeof c !== "string") return;');
w('        var clean = c.replace(/<[^>]+>/g,"").replace(/,/g,"").trim();');
w('        var m = clean.match(/(\\d{4,8})\\s*원$/);');
w('        if (m) { var v = parseInt(m[1]); if (v >= 1000 && v > rowAmt) rowAmt = v; }');
w('      });');
w('      totalAmount += rowAmt;');
w('');
w('      // 상품명/수량 파싱 — split("/") 방식');
w('      cell.forEach(function(c) {');
w('        if (typeof c !== "string") return;');
w('        var text = c.replace(/<[^>]+>/g,"").replace(/\\s+/g," ").trim();');
w('        if (text.indexOf("/") === -1) return;');
w('        var parts = text.split("/");');
w('        var namePart = parts[0].trim();');
w('        var qtyMatch = parts[1] && parts[1].match(/^\\s*(\\d+)\\s*개/);');
w('        if (!qtyMatch) return;');
w('        var qty = parseInt(qtyMatch[1]);');
w('        var name = namePart.replace(/\\([^)]*\\)/g,"").replace(/\\s+/g," ").trim();');
w('        if (name.length < 2 || name.length > 50 || qty <= 0 || qty >= 1000) return;');
w('        if (/배송비|배송|PJM|취소|주문번호/.test(name)) return;');
w('        if (!prodMap[name]) prodMap[name] = { qty: 0, amt: 0 };');
w('        prodMap[name].qty += qty;');
w('        prodMap[name].amt += rowAmt;');
w('      });');
w('    });');
w('  } catch(e) {');
w("    log('  [어드민 오류] ' + e.message);");
w('  }');
w('  return { orderCount: orderCount, prodMap: prodMap, totalAmount: totalAmount };');
w('}');
w('');

/* ── 곳간 Puppeteer ── */
w('// ── 곳간 Puppeteer ──────────────────────────────────────────────');
w('var fgPage = null, fgLoginTime = 0;');
w('');
w('async function fgLogin() {');
w('  var b = await getBrowser();');
w('  if (!fgPage || fgPage.isClosed()) {');
w('    fgPage = await b.newPage();');
w('    fgPage.on("dialog", function(d){ d.accept().catch(function(){}); });');
w('    await fgPage.evaluateOnNewDocument(function() {');
w('      Object.defineProperty(navigator, "webdriver", { get: function(){ return false; } });');
w('      window.chrome = { runtime: {} };');
w('      Object.defineProperty(navigator, "plugins", { get: function(){ return [1,2,3]; } });');
w('      Object.defineProperty(navigator, "languages", { get: function(){ return ["ko-KR","ko","en-US"]; } });');
w('    });');
w("    await fgPage.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');");
w('  }');
w("  log('  [곳간] 로그인 시작...');");
w('  await fgPage.goto(FG_LOGIN, { waitUntil: "networkidle2", timeout: 20000 });');
w("  try { await fgPage.waitForSelector('input[name=\"userId\"]', { timeout: 5000 }); } catch(e) {}");
w('');
w("  var idEl = await fgPage.$('input[name=\"userId\"]');");
w("  var pwEl = await fgPage.$('input[name=\"password\"]');");
w('  if (idEl && pwEl) {');
w('    await idEl.click({ clickCount: 3 }); await fgPage.keyboard.type(FG_ID);');
w('    await pwEl.click({ clickCount: 3 }); await fgPage.keyboard.type(FG_PW);');
w('  }');
w('  await sleep(300);');
w("  var loginBtn = await fgPage.$('button[type=\"submit\"],input[type=\"submit\"]').catch(function(){ return null; });");
w('  if (loginBtn) {');
w('    await Promise.all([');
w('      fgPage.waitForNavigation({ waitUntil: "networkidle2", timeout: 15000 }).catch(function(){}),');
w('      loginBtn.click()');
w('    ]);');
w('  } else if (pwEl) {');
w("    log('  [곳간] 버튼 못찾음 → Enter');");
w('    await Promise.all([');
w('      fgPage.waitForNavigation({ waitUntil: "networkidle2", timeout: 15000 }).catch(function(){}),');
w('      pwEl.press("Enter")');
w('    ]);');
w('  }');
w('  for (var i = 0; i < 8; i++) {');
w('    await sleep(1000);');
w('    if (fgPage.url().indexOf("Login") === -1) break;');
w('  }');
w("  log('  [곳간] 로그인 URL: ' + fgPage.url());");
w('  fgLoginTime = Date.now();');
w('}');
w('');
w('async function ensureFgLogin() {');
w('  if (Date.now() - fgLoginTime < 25*60*1000 && fgPage && !fgPage.isClosed()) return;');
w('  await fgLogin();');
w('}');
w('');

/* ── getGotganOrders ── */
w('async function getGotganOrders() {');
w('  await ensureFgLogin();');
w('  try {');
w("    await fgPage.goto(FG_BASE + '/NewOrder/deal01?order_status=20&formtype=C&pagesize=1000',");
w('      { waitUntil: "networkidle2", timeout: 15000 });');
w('    await sleep(1500);');
w('');
w('    if (fgPage.url().indexOf("Login") !== -1) {');
w("      log('  [곳간] 세션 만료 → 재로그인');");
w('      fgLoginTime = 0; await fgLogin();');
w("      await fgPage.goto(FG_BASE + '/NewOrder/deal01?order_status=20&formtype=C&pagesize=1000',");
w('        { waitUntil: "networkidle2", timeout: 15000 });');
w('      await sleep(1500);');
w('    }');
w('');
w('    var html = await fgPage.content();');
w('    var orderNums = new Set();');
w('    var pjmRe = /PJM[A-Z0-9-]+/g, pm;');
w('    while ((pm = pjmRe.exec(html)) !== null) orderNums.add(pm[0]);');
w("    log('  [곳간] PJM 주문번호 ' + orderNums.size + '개');");
w('');
w('    var result = await fgPage.evaluate(function() {');
w('      var map = {}, total = 0;');
w('      var rows = document.querySelectorAll("table tbody tr");');
w('      var debugCells = [];');
w('');
w('      rows.forEach(function(row, ri) {');
w('        var cells = Array.from(row.querySelectorAll("td")).map(function(td) {');
w('          return (td.innerText || td.textContent || "").replace(/\\s+/g," ").trim();');
w('        });');
w('        if (ri === 0) {');
w('          cells.slice(0,8).forEach(function(c,i){');
w('            debugCells.push(i + ": \\"" + c.slice(0,60) + "\\"");');
w('          });');
w('        }');
w('        if (cells.length < 6) return;');
w('        var prodCell = cells[5] || "";');
w('        if (!prodCell || prodCell.indexOf("/") === -1) return;');
w('');
w('        // split("/") 방식 파싱');
w('        var parts = prodCell.split("/");');
w('        var name = parts[0].trim();');
w('        var qtyPart = parts[1] || "";');
w('        var qtyMatch = qtyPart.match(/(\\d+)/);');
w('        if (!qtyMatch) return;');
w('        var qty = parseInt(qtyMatch[1]);');
w('');
w('        // 긴 괄호 제거, 앞쪽 숫자/특수문자 제거');
w('        name = name.replace(/\\s*\\([^)]{15,}\\)\\s*/g," ").trim();');
w('        name = name.replace(/^[\\d\\s\\[\\]\\(\\)\\·,]+/,"").trim();');
w('        if (name.length < 2 || qty <= 0 || qty >= 1000) return;');
w('        if (/배송|취소|결제|주문번호/.test(name)) return;');
w('');
w('        // 금액 파싱 (cells[6])');
w('        var amtCell = cells[6] || "";');
w('        var amt = 0;');
w('        var amtRe = /(\\d{1,3}(?:,\\d{3})+|\\d{4,8})\\s*원/g, am;');
w('        while ((am = amtRe.exec(amtCell)) !== null) {');
w('          var v = parseInt(am[1].replace(/,/g,""));');
w('          if (v > amt && v < 10000000) amt = v;');
w('        }');
w('');
w('        if (!map[name]) map[name] = { qty: 0, amt: 0 };');
w('        map[name].qty += qty;');
w('        map[name].amt += amt;');
w('        total += amt;');
w('      });');
w('');
w('      return { map: map, total: total, debugCells: debugCells, rowCount: rows.length };');
w('    });');
w('');
w("    log('  [곳간] tbody tr 수: ' + result.rowCount);");
w('    if (result.debugCells.length) {');
w("      log('  [곳간 cells] ' + result.debugCells.slice(0,7).join(' | '));");
w('    }');
w("    log('  [곳간] 상품 ' + Object.keys(result.map).length + '종, 총액 ' + result.total.toLocaleString() + '원');");
w('    return { orderCount: orderNums.size, prodMap: result.map, totalAmount: result.total };');
w('');
w('  } catch(e) {');
w("    log('  [곳간 오류] ' + e.message);");
w('    fgPage = null; fgLoginTime = 0;');
w('    return { orderCount: 0, prodMap: {}, totalAmount: 0 };');
w('  }');
w('}');
w('');

/* ── formatSection ── */
w('// ── 메시지 포맷 ──────────────────────────────────────────────────');
w('function formatSection(title, data) {');
w('  var orderCount  = data.orderCount  || 0;');
w('  var prodMap     = data.prodMap     || {};');
w('  var totalAmount = data.totalAmount || 0;');
w('  var entries = Object.entries(prodMap)');
w('    .map(function(pair) {');
w('      var v = typeof pair[1] === "object" ? pair[1] : { qty: pair[1], amt: 0 };');
w('      return [pair[0], v];');
w('    })');
w('    .filter(function(pair){ return pair[1].qty > 0; })');
w('    .sort(function(a,b){ return b[1].qty - a[1].qty; });');
w('  var total = totalAmount || entries.reduce(function(s,p){ return s + (p[1].amt||0); }, 0);');
w('  var msg = title + "\\n총 주문: <b>" + orderCount + "건</b>\\n";');
w('  if (total > 0) msg += "\\uD83D\\uDCB0 소계: <b>" + total.toLocaleString() + "원</b>\\n";');
w('  if (entries.length > 0) {');
w('    msg += "\\n\\uD83D\\uDCE6 상품별 수량\\n";');
w('    entries.slice(0,15).forEach(function(pair) {');
w('      var n = pair[0], v = pair[1];');
w('      var amtStr = v.amt > 0 ? " (" + v.amt.toLocaleString() + "원)" : "";');
w('      msg += "\\u2022 " + n + " <b>" + v.qty + "개</b>" + amtStr + "\\n";');
w('    });');
w('  } else {');
w('    msg += "  (상품 정보 없음)\\n";');
w('  }');
w('  return msg;');
w('}');
w('');

/* ── handleCommand ── */
w('// ── 명령 처리 ────────────────────────────────────────────────────');
w('var busy = false;');
w('');
w('async function handleCommand(cmd, chatId) {');
w("  log('처리: ' + cmd);");
w('');
w('  // /명령어리스트');
w('  if (cmd === "/명령어리스트" || cmd === "명령어리스트") {');
w('    await tgSend(');
w('      "\\uD83D\\uDCCB <b>동네곳간 주문현황봇 명령어</b>\\n"');
w('      + "\\u2500".repeat(22) + "\\n"');
w('      + "/주문건확인  \\u2192 어드민+곳간 통합 현황\\n"');
w('      + "/주문출력    \\u2192 곳간 주문 엑셀 출력\\n"');
w('      + "/승인상태    \\u2192 자동승인 봇 상태\\n"');
w('      + "/명령어리스트 \\u2192 이 목록\\n"');
w('      + "\\u2500".repeat(22) + "\\n"');
w('      + "\\uD83D\\uDCA1 슬래시(/) 없이도 동작",');
w('      chatId');
w('    );');
w('    return;');
w('  }');
w('');
w('  // /승인상태');
w('  if (cmd === "/승인상태" || cmd === "승인상태") {');
w('    await tgSend("\\uD83D\\uDFE2 gotgan-approve: 30초마다 인증대기 자동 승인 실행 중", chatId);');
w('    return;');
w('  }');
w('');
w('  // /주문출력');
w('  if (cmd === "/주문출력" || cmd === "주문출력") {');
w('    await tgSend("\\uD83D\\uDDA8\\uFE0F 곳간 주문 출력 시작... (약 30초 소요)", chatId);');
w('    (async function() {');
w('      var dlPage = null;');
w('      try {');
w('        var b2 = await getBrowser();');
w('        dlPage = await b2.newPage();');
w('        dlPage.on("dialog", function(d){ d.accept().catch(function(){}); });');
w('        var cdp = await dlPage.createCDPSession();');
w('        await cdp.send("Page.setDownloadBehavior", {');
w('          behavior: "allow",');
w('          downloadPath: require("path").join(require("os").homedir(), "Downloads")');
w('        });');
w("        await dlPage.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');");
w('        await dlPage.goto(FG_LOGIN, { waitUntil: "domcontentloaded", timeout: 20000 });');
w('        await sleep(1500);');
w("        var dId = await dlPage.$('input[name=\"userId\"]');");
w("        var dPw = await dlPage.$('input[name=\"password\"]');");
w('        if (dId) { await dId.click({ clickCount:3 }); await dId.type(FG_ID); }');
w('        if (dPw) { await dPw.click({ clickCount:3 }); await dPw.type(FG_PW); }');
w('        await sleep(500);');
w('        await Promise.all([');
w('          dlPage.waitForNavigation({ waitUntil: "networkidle2", timeout: 15000 }).catch(function(){}),');
w('          dPw ? dPw.press("Enter") : Promise.resolve()');
w('        ]);');
w('        await sleep(2000);');
w('        if (dlPage.url().indexOf("dongnaegotgan.flexgate.co.kr") === -1) {');
w('          await dlPage.close();');
w('          await tgSend("\\u274C 곳간 로그인 실패.", chatId); return;');
w('        }');
w("        await dlPage.goto(FG_BASE + '/NewOrder/deal01?order_status=30&formtype=A&pagesize=1000',");
w('          { waitUntil: "networkidle2", timeout: 30000 });');
w('        await sleep(2000);');
w('        await dlPage.waitForFunction(');
w('          function(){ return document.querySelectorAll("input[name=\\"chk\\"]").length > 0; },');
w('          { timeout: 15000, polling: 500 }');
w('        ).catch(function(){});');
w('        var cnt = await dlPage.evaluate(function(){');
w('          return document.querySelectorAll("input[name=\\"chk\\"]").length;');
w('        });');
w('        if (cnt === 0) {');
w('          await dlPage.close();');
w('          await tgSend("\\uD83D\\uDCED 배송준비 주문이 없습니다.", chatId); return;');
w('        }');
w('        await dlPage.evaluate(function() {');
w('          document.getElementById("chkCheckDataAll").click();');
w('          document.getElementById("customexcelFrm").value = "94";');
w('        });');
w('        await sleep(500);');
w('        var createPromise = dlPage.waitForResponse(');
w('          function(r){ return r.url().indexOf("CreateExcelIfile") !== -1; },');
w('          { timeout: 30000 }');
w('        ).catch(function(){ return null; });');
w('        await dlPage.evaluate(function(){ orderExcelDownload(3); });');
w('        var fileName = null;');
w('        var cRes = await createPromise;');
w('        if (cRes) {');
w('          var txt = await cRes.text().catch(function(){ return ""; });');
w('          var fm = txt.match(/order_\\d+\\.xlsx/);');
w('          if (fm) fileName = fm[0];');
w('          else { try { fileName = JSON.parse(txt).fileName || ""; } catch(e) {} }');
w('        }');
w('        if (!fileName) {');
w('          await dlPage.close();');
w('          await tgSend("\\u274C 파일 생성 실패.", chatId); return;');
w('        }');
w('        await sleep(2000);');
w("        await dlPage.goto(FG_BASE + '/NewOrder/ExcelDownload?fileName=' + encodeURIComponent(fileName),");
w('          { waitUntil: "domcontentloaded", timeout: 20000 }).catch(function(){});');
w('        await sleep(5000);');
w('        await dlPage.close();');
w('        await tgSend("\\u2705 주문 엑셀 다운로드 완료! (" + cnt + "건)\\n자동 출력 처리 중..", chatId);');
w('      } catch(e) {');
w('        if (dlPage) await dlPage.close().catch(function(){});');
w('        await tgSend("\\u274C 주문출력 오류: " + e.message, chatId);');
w('      }');
w('    })();');
w('    return;');
w('  }');
w('');
w('  // /주문건확인');
w('  if (cmd === "/주문건확인" || cmd === "주문건확인") {');
w('    if (busy) { await tgSend("\\u23F3 조회 중입니다...", chatId); return; }');
w('    busy = true;');
w('    try {');
w("      var now = new Date().toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' });");
w("      log('통합 주문건 조회...');");
w('      await tgSend("\\uD83D\\uDD0D 조회 중..", chatId);');
w('      var results = await Promise.allSettled([getAdminOrders(), getGotganOrders()]);');
w('      var aD = results[0].status === "fulfilled" ? results[0].value : null;');
w('      var fD = results[1].status === "fulfilled" ? results[1].value : null;');
w('');
w('      var msg = "\\uD83D\\uDCCA <b>주문현황</b>  " + now + "\\n" + "\\u2500".repeat(22) + "\\n\\n";');
w('      msg += aD ? formatSection("\\uD83C\\uDFEA <b>[어드민] 상품쇼핑몰</b>", aD) : "\\uD83C\\uDFEA 어드민 조회 실패\\n";');
w('      msg += "\\n";');
w('      msg += fD ? formatSection("\\uD83D\\uDED2 <b>[곳간] flexgate</b>", fD)     : "\\uD83D\\uDED2 곳간 조회 실패\\n";');
w('');
w('      var adminTotal  = (aD && aD.totalAmount) ? aD.totalAmount : 0;');
w('      var gotganTotal = (fD && fD.totalAmount) ? fD.totalAmount : 0;');
w('      var grandTotal  = adminTotal + gotganTotal;');
w('      if (grandTotal > 0) {');
w('        msg += "\\n" + "\\u2500".repeat(22) + "\\n";');
w('        msg += "\\uD83D\\uDCB5 <b>합산 총액: " + grandTotal.toLocaleString() + "원</b>\\n";');
w('        if (adminTotal  > 0) msg += "   어드민: " + adminTotal.toLocaleString()  + "원\\n";');
w('        if (gotganTotal > 0) msg += "   곳간: "   + gotganTotal.toLocaleString() + "원\\n";');
w('      }');
w('      await tgSend(msg, chatId);');
w("      log('발송 완료');");
w('    } catch(e) {');
w("      log('오류: ' + e.message);");
w('      await tgSend("\\u274C 오류: " + e.message, chatId);');
w('    } finally {');
w('      busy = false;');
w('    }');
w('    return;');
w('  }');
w('}');
w('');

/* ── 폴링 ── */
w('// ── 폴링 ─────────────────────────────────────────────────────────');
w('var lastUpdateId = 0, polling = false;');
w('var CMDS = [');
w('  "/주문건확인","주문건확인",');
w('  "/주문출력",  "주문출력",');
w('  "/승인상태",  "승인상태",');
w('  "/명령어리스트","명령어리스트"');
w('];');
w('');
w('async function poll() {');
w('  if (polling) return; polling = true;');
w('  try {');
w('    var updates = await tgGetUpdates(lastUpdateId);');
w('    for (var i = 0; i < updates.length; i++) {');
w('      var u = updates[i];');
w('      lastUpdateId = u.update_id + 1;');
w('      var msg = u.message || u.edited_message;');
w('      if (!msg || !msg.text) continue;');
w('      var text   = msg.text.trim().split(" ")[0];');
w('      var chatId = String(msg.chat.id);');
w('      if (chatId !== TG_CHAT) continue;');
w("      log('수신: \"' + text + '\"');");
w('      if (CMDS.indexOf(text) !== -1) handleCommand(text, chatId);');
w('    }');
w("  } catch(e) { log('poll 오류: ' + e.message); }");
w('  finally { polling = false; }');
w('}');
w('');
w("log('\\uD83E\\uDD16 주문현황 봇 v14');");
w("log('   /주문건확인  /주문출력  /승인상태  /명령어리스트');");
w('setInterval(poll, 3000);');
w('poll();');
w('process.on("SIGINT",  function(){ if (browser) browser.close(); process.exit(0); });');
w('process.on("SIGTERM", function(){ if (browser) browser.close(); process.exit(0); });');

/* ─── 파일 출력 ─── */
fs.writeFileSync(TARGET, lines.join('\n'), 'utf8');

console.log('✅ tg_status_bot.js v14 작성 완료!');
console.log('   - 어드민: Puppeteer 로그인 (HTTP 쿠키 문제 해결)');
console.log('   - tgSend: 재시도 3회 (2초 간격)');
console.log('   - 곳간: split("/") 파싱 유지');
console.log('   - 정규식 백슬래시 오염 없음');
console.log('');
console.log('다음 실행:');
console.log('   pm2 restart gotgan-status');
console.log('   pm2 logs gotgan-status --lines 30 --nostream');