/**
 * write_new_bot5.js
 * tg_status_bot.js v13
 * - 정규식 이중 이스케이프 완전 수정 (\\s, \\d 등)
 * - evaluate() DOM cells[5] 방식 (debug_orders.js 검증)
 * - 명령어: /주문건확인 /주문출력 /승인상태 /명령어리스트
 */
const fs = require('fs');
const path = require('path');

const TARGET = path.join(__dirname, 'tg_status_bot.js');
const bak = TARGET.replace('.js', `.v12bak_${Date.now()}.js`);
if (fs.existsSync(TARGET)) {
  fs.copyFileSync(TARGET, bak);
  console.log(`백업: ${path.basename(bak)}`);
}

// 정규식 이스케이프 문제 해결: 파일 내용을 배열로 작성
const lines = [];
const w = (s) => lines.push(s);

w('/**');
w(' * tg_status_bot.js v13');
w(' * 명령어: /주문건확인 /주문출력 /승인상태 /명령어리스트');
w(' */');
w("require('dotenv').config({ path: require('path').join(__dirname, '.env') });");
w("const https = require('https');");
w("const http  = require('http');");
w("const puppeteer = require('puppeteer');");
w('');
w("const TG_TOKEN   = process.env.TG_TOKEN || '8796752509:AAFX54QxpY0SCXxAwpOXqqxVrKEvlZhSNKc';");
w("const TG_CHAT    = process.env.TG_CHAT  || '6097520392';");
w("const ADMIN_HOST = 'dongnaegotgan.adminplus.co.kr';");
w("const ADMIN_URL  = `https://${ADMIN_HOST}/admin/`;");
w("const ADMIN_ID   = process.env.ADMIN_ID || 'dongnaegotgan';");
w("const ADMIN_PW   = process.env.ADMIN_PW || 'rhtrks12!@';");
w("const FG_URL     = 'https://dongnaegotgan.flexgate.co.kr';");
w("const FG_LOGIN   = 'https://intro.flexgate.co.kr/Mypage/Login';");
w("const FG_ID      = process.env.FG_ID || 'dongnaegotgan';");
w("const FG_PW      = process.env.FG_PW || 'rhtrks12!@';");
w('');
w("function log(m) { console.log(`[${new Date().toLocaleTimeString('ko-KR')}] ${m}`); }");
w('function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }');
w('');
w('function req(options, body = null) {');
w('  return new Promise((resolve, reject) => {');
w("    const mod = (options.protocol === 'http:' || options.hostname === 'localhost') ? http : https;");
w('    const r = mod.request(options, res => {');
w("      let data = '';");
w("      res.on('data', d => data += d);");
w("      res.on('end', () => resolve({ status: res.statusCode, headers: res.headers, body: data }));");
w('    });');
w('    r.on(\'error\', reject);');
w('    if (body) r.write(body);');
w('    r.end();');
w('  });');
w('}');
w('function parseCookies(arr) {');
w('  const c = {};');
w("  (arr||[]).forEach(s => {");
w("    const [kv] = s.split(';'); const [k,v] = kv.split('=');");
w("    if (k) c[k.trim()] = (v||'').trim();");
w('  });');
w('  return c;');
w('}');
w('function cookieStr(c) { return Object.entries(c).map(([k,v]) => `${k}=${v}`).join(\'; \'); }');
w('');
w('// ── 텔레그램 ─────────────────────────────────────────────────────────');
w('async function tgSend(msg, chatId = TG_CHAT) {');
w('  const body = JSON.stringify({ chat_id: chatId, text: msg, parse_mode: \'HTML\' });');
w('  await req({');
w("    hostname: 'api.telegram.org', path: `/bot${TG_TOKEN}/sendMessage`,");
w("    method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) }");
w('  }, body).catch(e => log(`tgSend 오류: ${e.message}`));');
w('}');
w('async function tgGetUpdates(offset) {');
w('  const res = await req({');
w("    hostname: 'api.telegram.org',");
w('    path: `/bot${TG_TOKEN}/getUpdates?offset=${offset}&timeout=20&limit=10`, method: \'GET\'');
w('  }).catch(() => null);');
w('  if (!res) return [];');
w('  try { const d = JSON.parse(res.body); return d.ok ? d.result : []; } catch { return []; }');
w('}');
w('');
w('// ── 어드민플러스 ───────────────────────────────────────────────────────');
w('let adminCookies = {}, adminLoginTime = 0;');
w('');
w('async function adminLogin() {');
w("  const loginBody = new URLSearchParams({ id: ADMIN_ID, pw: ADMIN_PW, mode: 'login' }).toString();");
w('  let cookies = {};');
w('  let opts = {');
w("    hostname: ADMIN_HOST, path: '/admin/login.php', method: 'POST',");
w('    headers: {');
w("      'Content-Type': 'application/x-www-form-urlencoded',");
w('      \'Content-Length\': Buffer.byteLength(loginBody),');
w("      'Referer': ADMIN_URL, 'User-Agent': 'Mozilla/5.0'");
w('    }');
w('  };');
w('  let nextBody = loginBody;');
w('  for (let hop = 0; hop < 6; hop++) {');
w('    const res = await req(opts, nextBody);');
w("    Object.assign(cookies, parseCookies(res.headers['set-cookie']));");
w("    const loc = res.headers['location'];");
w('    if (!loc) break;');
w('    let h = ADMIN_HOST, p = loc;');
w("    if (loc.startsWith('http')) {");
w('      try { const u = new URL(loc); h = u.hostname; p = u.pathname + u.search; } catch(e) {}');
w('    }');
w("    opts = { hostname: h, path: p, method: 'GET',");
w("      headers: { 'Cookie': cookieStr(cookies), 'User-Agent': 'Mozilla/5.0', 'Referer': ADMIN_URL } };");
w('    nextBody = null;');
w('  }');
w('  adminCookies = cookies;');
w('  adminLoginTime = Date.now();');
w('  log(`  [어드민] 로그인, 쿠키: ${Object.keys(cookies).join(\', \') || \'없음\'}`);');
w('}');
w('');
w('async function ensureAdmin() {');
w('  if (Date.now() - adminLoginTime < 20*60*1000 && Object.keys(adminCookies).length) return;');
w('  await adminLogin();');
w('}');
w('');
w('async function getAdminOrders() {');
w('  await ensureAdmin();');
w('  const todayKST = new Date(Date.now() + 9*60*60*1000).toISOString().slice(0,10);');
w('  let orderCount = 0;');
w('  try {');
w('    const sr = await req({');
w("      hostname: ADMIN_HOST, path: '/admin/xml/real.stats.json.php', method: 'POST',");
w('      headers: {');
w("        'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': 0,");
w("        'Cookie': cookieStr(adminCookies), 'Referer': ADMIN_URL,");
w("        'User-Agent': 'Mozilla/5.0', 'X-Requested-With': 'XMLHttpRequest'");
w('      }');
w("    }, '');");
w('    const stats = JSON.parse(sr.body);');
w('    orderCount = parseInt(stats.spnNew5) || 0;');
w('    log(`  [어드민 stats] 신규(spnNew5)=${stats.spnNew5}, 오늘전체(spnNew8)=${stats.spnNew8}`);');
w('  } catch(e) { log(`  [어드민 stats 오류] ${e.message}`); }');
w('');
w('  const params = new URLSearchParams({');
w("    proc: 'json', mod: 'order', actpage: 'od.list.bd',");
w("    status: '10', datefld: 'b.regdate',");
w('    sdate: JSON.stringify({ start: todayKST, end: todayKST }),');
w("    bizgrp: 'all', searchtype: 'all', searchval: '',");
w("    _search: 'false', rows: '500', page: '1', sidx: 'regdate', sord: 'desc'");
w('  });');
w('');
w('  const prodMap = {};');
w('  let totalAmount = 0;');
w('  try {');
w('    const listRes = await req({');
w('      hostname: ADMIN_HOST,');
w('      path: `/admin/order/json/od.list.bd.php?${params}`, method: \'GET\',');
w('      headers: {');
w("        'Cookie': cookieStr(adminCookies), 'Referer': ADMIN_URL,");
w("        'User-Agent': 'Mozilla/5.0', 'X-Requested-With': 'XMLHttpRequest'");
w('      }');
w('    });');
w('    let data;');
w('    try { data = JSON.parse(listRes.body); }');
w('    catch(e) {');
w("      log('  [어드민] 세션만료, 재로그인');");
w('      adminLoginTime = 0; await adminLogin();');
w('      const r2 = await req({');
w('        hostname: ADMIN_HOST,');
w('        path: `/admin/order/json/od.list.bd.php?${params}`, method: \'GET\',');
w("        headers: { 'Cookie': cookieStr(adminCookies), 'Referer': ADMIN_URL,");
w("          'User-Agent': 'Mozilla/5.0', 'X-Requested-With': 'XMLHttpRequest' }");
w('      });');
w('      data = JSON.parse(r2.body);');
w('    }');
w('    const rows = data.rows || [];');
w('    const listCount = parseInt(data.records) || rows.length;');
w('    log(`  [어드민] 신규주문 ${listCount}건, rows=${rows.length}`);');
w('    if (!orderCount) orderCount = listCount;');
w('    rows.forEach((row, ri) => {');
w('      const cell = Array.isArray(row.cell) ? row.cell : [];');
w('      if (ri === 0) log(`  [어드민 cell샘플] ${JSON.stringify(cell).slice(0,150)}`);');
w('      let rowAmt = 0;');
w('      cell.forEach(c => {');
w("        if (typeof c !== 'string') return;");
// 정규식: clean.match(/(\d{4,8})\s*원?$/)
w("        const clean = c.replace(/<[^>]+>/g,'').replace(/,/g,'').trim();");
w('        const m = clean.match(/(\\d{4,8})\\s*원?$/);');
w('        if (m) { const v = parseInt(m[1]); if (v >= 1000 && v > rowAmt) rowAmt = v; }');
w('      });');
w('      totalAmount += rowAmt;');
w('      cell.forEach(c => {');
w("        if (typeof c !== 'string') return;");
// 정규식: text.replace(/\s+/g,' ')
w("        const text = c.replace(/<[^>]+>/g,'').replace(/\\s+/g,' ').trim();");
w("        const main = text.split('·')[0].trim();");
// 정규식: main.match(/^(.{2,50}?)\s*\/\s*(\d+)\s*개?/)
w('        const m1 = main.match(/^(.{2,50}?)\\s*\\/\\s*(\\d+)\\s*개?/);');
w('        if (m1) {');
// 정규식: m1[1].replace(/\([^)]*\)/g,'')
w("          const name = m1[1].replace(/\\([^)]*\\)/g,'').trim();");
w('          const qty = parseInt(m1[2]);');
w('          if (name.length >= 2 && name.length <= 40 && qty > 0 && qty < 1000 &&');
w('              !/배송비|배송|PJM|입금|원$|주문/.test(name)) {');
w("            if (!prodMap[name]) prodMap[name] = { qty: 0, amt: 0 };");
w('            prodMap[name].qty += qty;');
w('            prodMap[name].amt += rowAmt;');
w('          }');
w('        }');
w('      });');
w('    });');
w('  } catch(e) { log(`  [어드민 목록 오류] ${e.message}`); }');
w('  return { orderCount, prodMap, totalAmount };');
w('}');
w('');
w('// ── 곳간 Puppeteer ────────────────────────────────────────────────────');
w('let fgBrowser = null, fgPage = null, fgLoginTime = 0;');
w('');
w('async function ensureFgBrowser() {');
w("  if (fgBrowser && fgBrowser.isConnected()) return;");
w("  log('  [곳간] 새 브라우저 시작...');");
w('  fgBrowser = await puppeteer.launch({');
w('    headless: true,');
w("    args: ['--no-sandbox','--disable-setuid-sandbox','--lang=ko-KR',");
w("           '--disable-blink-features=AutomationControlled','--disable-web-security'],");
w('    defaultViewport: { width: 1440, height: 900 },');
w('    ignoreHTTPSErrors: true,');
w('  });');
w('  fgPage = await fgBrowser.newPage();');
w('  fgPage.on(\'dialog\', d => d.accept().catch(() => {}));');
w('  await fgPage.evaluateOnNewDocument(() => {');
w('    Object.defineProperty(navigator, \'webdriver\', { get: () => false });');
w('    window.chrome = { runtime: {} };');
w('    Object.defineProperty(navigator, \'plugins\', { get: () => [1,2,3] });');
w("    Object.defineProperty(navigator, 'languages', { get: () => ['ko-KR','ko','en-US'] });");
w('  });');
w("  await fgPage.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');");
w('}');
w('');
w('async function fgLogin() {');
w('  await ensureFgBrowser();');
w("  log('  [곳간] 로그인 시작...');");
w('  await fgPage.goto(FG_LOGIN, { waitUntil: \'networkidle2\', timeout: 20000 });');
w("  try { await fgPage.waitForSelector('input[name=\"userId\"]', { timeout: 5000 }); } catch(e) {}");
w('  await fgPage.evaluate(() => {');
w('    const u = document.querySelector(\'input[name="userId"]\');');
w('    const p = document.querySelector(\'input[name="password"]\');');
w("    if (u) u.value = ''; if (p) p.value = '';");
w('  });');
w("  const idEl = await fgPage.$('input[name=\"userId\"]');");
w("  const pwEl = await fgPage.$('input[name=\"password\"]');");
w('  if (idEl && pwEl) {');
w('    await idEl.click({ clickCount: 3 }); await fgPage.keyboard.type(FG_ID);');
w('    await pwEl.click({ clickCount: 3 }); await fgPage.keyboard.type(FG_PW);');
w('  }');
w('  await sleep(300);');
w("  const loginBtn = await fgPage.$('button[type=\"submit\"], input[type=\"submit\"]').catch(() => null);");
w('  if (loginBtn) {');
w('    await Promise.all([');
w("      fgPage.waitForNavigation({ waitUntil: 'networkidle2', timeout: 15000 }).catch(() => {}),");
w('      loginBtn.click(),');
w('    ]);');
w('  } else if (pwEl) {');
w("    log('  [곳간] 버튼 못찾음 → Enter');");
w('    await Promise.all([');
w("      fgPage.waitForNavigation({ waitUntil: 'networkidle2', timeout: 15000 }).catch(() => {}),");
w("      pwEl.press('Enter'),");
w('    ]);');
w('  }');
w('  for (let i = 0; i < 8; i++) {');
w('    await sleep(1000);');
w("    if (!fgPage.url().includes('Login')) break;");
w('  }');
w('  log(`  [곳간] 로그인 URL: ${fgPage.url()}`);');
w('  fgLoginTime = Date.now();');
w('}');
w('');
w('async function ensureFgLogin() {');
w("  if (Date.now() - fgLoginTime < 25*60*1000 && fgBrowser?.isConnected()) return;");
w('  await fgLogin();');
w('}');
w('');
w('async function getGotganOrders() {');
w('  await ensureFgLogin();');
w('  try {');
w('    await fgPage.goto(`${FG_URL}/NewOrder/deal01?order_status=10&formtype=A&pagesize=1000`,');
w("      { waitUntil: 'networkidle2', timeout: 15000 });");
w('    await sleep(1500);');
w('    const url = fgPage.url();');
w("    if (url.includes('Login') || url.includes('login')) {");
w("      log('  [곳간] 세션 만료, 재로그인...');");
w('      fgLoginTime = 0; await fgLogin();');
w("      if (!fgPage.url().includes('Login')) {");
w('        await fgPage.goto(`${FG_URL}/NewOrder/deal01?order_status=10&formtype=A&pagesize=1000`,');
w("          { waitUntil: 'networkidle2', timeout: 15000 });");
w('        await sleep(1500);');
w('      }');
w('    }');
w('');
w('    const html = await fgPage.content();');
w('    const orderNums = new Set();');
w('    for (const m of html.matchAll(/PJM[A-Z0-9-]+/g)) orderNums.add(m[0]);');
w('    log(`  [곳간] PJM 주문번호 ${orderNums.size}개`);');
w('');
w('    if (orderNums.size === 0) {');
w('      await fgPage.goto(`${FG_URL}/NewOrder/deal01?order_status=20&formtype=A&pagesize=1000`,');
w("        { waitUntil: 'networkidle2', timeout: 15000 });");
w('      await sleep(800);');
w('      const html2 = await fgPage.content();');
w('      for (const m of html2.matchAll(/PJM[A-Z0-9-]+/g)) orderNums.add(m[0]);');
w('      log(`  [곳간 status=20] PJM ${orderNums.size}개`);');
w('    }');
w('');
w('    // ★ evaluate() DOM 직접 접근 — debug_orders.js 검증 완료');
w('    const result = await fgPage.evaluate(() => {');
w('      const map = {};');
w('      let total = 0;');
w('      const rows = document.querySelectorAll(\'table tbody tr\');');
w('      rows.forEach((row, ri) => {');
w('        const cells = [...row.querySelectorAll(\'td\')]');
// 주의: evaluate() 안의 문자열은 런타임에 평가됨. 정규식은 일반 JS 정규식으로 동작
// 여기서는 문자열이 아니라 함수 참조로 전달됨 → 정규식 백슬래시 그대로 써야 함
// 하지만 이 전체가 lines 배열 → 파일에 직접 써짐 → 정상 JS 파일이 됨
// 따라서 이 부분의 정규식은 정규 JS 정규식 그대로 쓰면 됨
w("          .map(td => (td.innerText || td.textContent || '').replace(/\\s+/g, ' ').trim());");
w('        if (cells.length < 6) return;');
w("        const prodCell = cells[5] || '';");
w('        if (!prodCell) return;');
w('        // 슬래시 앞뒤 공백 유무 상관없이 파싱');
w('        const m = prodCell.match(/^(.+?)\\s*\\/\\s*(\\d+)\\s*개/);');
w('        if (!m) return;');
w("        let name = m[1].trim();");
w('        const qty = parseInt(m[2]);');
w('        // 괄호 안 긴 설명 제거');
w("        name = name.replace(/\\s*\\([^)]{15,}\\)\\s*/g, ' ').trim();");
w("        name = name.replace(/^[\\d\\s\\[\\]\\(\\)·,]+/, '').trim();");
w('        if (name.length < 2 || qty <= 0 || qty >= 1000) return;');
w('        if (/배송비|배송|주소|취소|결제|입금/.test(name)) return;');
w("        const amtCell = cells[6] || '';");
w('        let amt = 0;');
w('        const amtMs = amtCell.match(/(\\d{1,3}(?:,\\d{3})+|\\d{4,8})\\s*원/g);');
w('        if (amtMs) amtMs.forEach(a => {');
w("          const v = parseInt(a.replace(/[,원]/g,''));");
w('          if (v > amt && v < 10000000) amt = v;');
w('        });');
w("        if (!map[name]) map[name] = { qty: 0, amt: 0 };");
w('        map[name].qty += qty;');
w('        map[name].amt += amt;');
w('        total += amt;');
w('      });');
w('      const firstRow = document.querySelector(\'table tbody tr\');');
w('      const debugCells = firstRow');
w("        ? [...firstRow.querySelectorAll('td')].map((td, i) =>");
w("            i + ': \"' + (td.innerText||'').replace(/\\s+/g,' ').trim().slice(0,60) + '\"'");
w('          )');
w("        : ['행 없음'];");
w('      return { map, total, debugCells, rowCount: rows.length };');
w('    });');
w('');
w('    log(`  [곳간] tbody tr 수: ${result.rowCount}`);');
w('    log(`  [곳간 디버그 cells] ${result.debugCells.slice(0,7).join(\' | \')}`);');
w('    log(`  [곳간] 상품 ${Object.keys(result.map).length}종, 총액 ${result.total.toLocaleString()}원`);');
w('    return { orderCount: orderNums.size, prodMap: result.map, totalAmount: result.total };');
w('');
w('  } catch(e) {');
w('    log(`  [곳간 오류] ${e.message}`);');
w('    try { await fgBrowser?.close(); } catch(_) {}');
w('    fgBrowser = null; fgPage = null; fgLoginTime = 0;');
w('    return { orderCount: 0, prodMap: {}, totalAmount: 0 };');
w('  }');
w('}');
w('');
w('// ── 메시지 포맷 ───────────────────────────────────────────────────────');
w('function formatSection(title, data) {');
w('  const { orderCount, prodMap, totalAmount } = data;');
w('  const entries = Object.entries(prodMap)');
w('    .map(([n, v]) => [n, typeof v === \'object\' ? v : { qty: v, amt: 0 }])');
w('    .filter(([,v]) => v.qty > 0)');
w('    .sort((a,b) => b[1].qty - a[1].qty);');
w('  const total = totalAmount || entries.reduce((s,[,v]) => s + (v.amt||0), 0);');
w('  const totalStr = total > 0 ? `  💰 소계: <b>${total.toLocaleString()}원</b>\\n` : \'\';');
w('  let msg = `${title}\\n총 주문: <b>${orderCount}건</b>\\n${totalStr}`;');
w('  if (entries.length > 0) {');
w('    msg += `\\n📦 상품별 수량\\n`;');
w('    entries.slice(0,15).forEach(([n,v]) => {');
w('      const amtStr = v.amt > 0 ? ` (${v.amt.toLocaleString()}원)` : \'\';');
w('      msg += `  • ${n} <b>${v.qty}개</b>${amtStr}\\n`;');
w('    });');
w('  } else {');
w('    msg += `  (상품 정보 없음)\\n`;');
w('  }');
w('  return msg;');
w('}');
w('');
w('// ── 명령 처리 ─────────────────────────────────────────────────────────');
w('let busy = false;');
w('');
w('async function handleCommand(cmd, chatId) {');
w('  log(`처리: ${cmd}`);');
w('');
w("  if (cmd === '/명령어리스트' || cmd === '명령어리스트') {");
w('    await tgSend(');
w("      `📋 <b>동네곳간 주문현황봇 명령어</b>\\n` +");
w("      `${'─'.repeat(22)}\\n` +");
w("      `/주문건확인 — 어드민+곳간 통합 주문현황\\n` +");
w("      `/주문출력   — 곳간 주문 엑셀 출력\\n` +");
w("      `/승인상태   — 자동승인 봇 실행 상태\\n` +");
w("      `/명령어리스트 — 이 목록 보기\\n` +");
w("      `${'─'.repeat(22)}\\n` +");
w("      `💡 슬래시(/) 없이도 동작\\n` +");
w("      `   예) 주문건확인`,");
w('      chatId');
w('    );');
w('    return;');
w('  }');
w('');
w("  if (cmd === '/승인상태' || cmd === '승인상태') {");
w("    await tgSend('🔔 gotgan-approve: 30초 간격 인증대기 자동 승인 실행 중', chatId);");
w('    return;');
w('  }');
w('');
w("  if (cmd === '/주문출력' || cmd === '주문출력') {");
w("    await tgSend('📥 곳간 주문 출력 시작... (약 30초 소요)', chatId);");
w('    (async () => {');
w('      let dlBrowser = null;');
w('      try {');
w("        const os = require('os');");
w("        const DOWNLOADS = require('path').join(os.homedir(), 'Downloads');");
w("        const FG_BASE = 'https://dongnaegotgan.flexgate.co.kr';");
w("        const FG_INTRO = 'https://intro.flexgate.co.kr';");
w('        dlBrowser = await puppeteer.launch({');
w('          headless: true,');
w("          args: ['--no-sandbox','--disable-setuid-sandbox','--disable-blink-features=AutomationControlled'],");
w('          defaultViewport: { width: 1440, height: 900 },');
w('        });');
w('        const dlPage = await dlBrowser.newPage();');
w('        dlPage.on(\'dialog\', d => d.accept().catch(() => {}));');
w('        const cdp = await dlPage.createCDPSession();');
w("        await cdp.send('Page.setDownloadBehavior', { behavior: 'allow', downloadPath: DOWNLOADS });");
w('        await dlPage.evaluateOnNewDocument(() => { Object.defineProperty(navigator,\'webdriver\',{get:()=>false}); });');
w("        await dlPage.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');");
w('        await dlPage.goto(`${FG_INTRO}/Mypage/Login`, { waitUntil: \'domcontentloaded\', timeout: 20000 });');
w('        await sleep(1500);');
w("        const idEl = await dlPage.$('input[name=\"userId\"]');");
w("        const pwEl = await dlPage.$('input[name=\"password\"]');");
w('        if (idEl) { await idEl.click({clickCount:3}); await idEl.type(FG_ID); }');
w('        if (pwEl) { await pwEl.click({clickCount:3}); await pwEl.type(FG_PW); }');
w('        await sleep(500);');
w('        await Promise.all([');
w("          dlPage.waitForNavigation({ waitUntil: 'networkidle2', timeout: 15000 }).catch(() => {}),");
w('          pwEl ? pwEl.press(\'Enter\') : Promise.resolve(),');
w('        ]);');
w('        await sleep(2000);');
w("        if (!dlPage.url().includes('dongnaegotgan.flexgate.co.kr')) {");
w('          await dlBrowser.close();');
w("          await tgSend('❌ 곳간 로그인 실패.', chatId);");
w('          return;');
w('        }');
w('        await dlPage.goto(`${FG_BASE}/NewOrder/deal01?order_status=30&formtype=A&pagesize=1000`,');
w("          { waitUntil: 'networkidle2', timeout: 30000 });");
w('        await sleep(2000);');
w("        await dlPage.waitForFunction(() => document.querySelectorAll('input[name=\"chk\"]').length > 0,");
w('          { timeout: 15000, polling: 500 }).catch(() => {});');
w("        const cnt = await dlPage.evaluate(() => document.querySelectorAll('input[name=\"chk\"]').length);");
w('        if (cnt === 0) {');
w('          await dlBrowser.close();');
w("          await tgSend('📭 배송준비중 주문 없음.', chatId);");
w('          return;');
w('        }');
w('        await dlPage.evaluate(() => {');
w("          document.getElementById('chkCheckDataAll').click();");
w("          document.getElementById('customexcelFrm').value = '94';");
w('        });');
w('        await sleep(500);');
w('        const createPromise = dlPage.waitForResponse(');
w("          r => r.url().includes('CreateExcelIfile'), { timeout: 30000 }");
w('        ).catch(() => null);');
w('        await dlPage.evaluate(() => orderExcelDownload(3));');
w('        let fileName = null;');
w('        const res = await createPromise;');
w('        if (res) {');
w("          const text = await res.text().catch(() => '');");
w('          const m = text.match(/order_\\d+\\.xlsx/);');
w('          if (m) fileName = m[0];');
w("          else { try { fileName = JSON.parse(text).fileName || ''; } catch(e) {} }");
w('        }');
w("        if (!fileName) { await dlBrowser.close(); await tgSend('❌ 파일 생성 실패.', chatId); return; }");
w('        await sleep(2000);');
w('        await dlPage.goto(`${FG_BASE}/NewOrder/ExcelDownload?fileName=${encodeURIComponent(fileName)}`,');
w("          { waitUntil: 'domcontentloaded', timeout: 20000 }).catch(() => {});");
w('        await sleep(5000);');
w('        await dlBrowser.close();');
w('        await tgSend(`✅ 주문 엑셀 다운로드 완료! (${cnt}건)\\n자동 출력 처리 중..`, chatId);');
w('      } catch(e) {');
w('        if (dlBrowser) await dlBrowser.close().catch(() => {});');
w('        await tgSend(`❌ 주문출력 오류: ${e.message}`, chatId);');
w('      }');
w('    })();');
w('    return;');
w('  }');
w('');
w("  if (cmd === '/주문건확인' || cmd === '주문건확인') {");
w("    if (busy) { await tgSend('⏳ 조회 중입니다...', chatId); return; }");
w('    busy = true;');
w('    try {');
w("      const now = new Date().toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' });");
w("      log('통합 주문건 조회...');");
w("      await tgSend('🔍 조회 중..', chatId);");
w('      const [aR, fR] = await Promise.allSettled([getAdminOrders(), getGotganOrders()]);');
w("      const aD = aR.status === 'fulfilled' ? aR.value : null;");
w("      const fD = fR.status === 'fulfilled' ? fR.value : null;");
w("      let msg = `📊 <b>주문현황</b>  ${now}\\n${'─'.repeat(22)}\\n\\n`;");
w("      msg += aD ? formatSection('🏪 <b>[어드민] 상품쇼핑몰</b>', aD) : '🏪 어드민 조회 실패\\n';");
w("      msg += '\\n';");
w("      msg += fD ? formatSection('🛒 <b>[곳간] flexgate</b>', fD) : '🛒 곳간 조회 실패\\n';");
w('      const adminTotal = aD?.totalAmount || 0;');
w('      const gotganTotal = fD?.totalAmount || 0;');
w('      const grandTotal = adminTotal + gotganTotal;');
w('      if (grandTotal > 0) {');
w("        msg += `\\n${'─'.repeat(22)}\\n💵 <b>합산 총액: ${grandTotal.toLocaleString()}원</b>\\n`;");
w('        if (adminTotal > 0) msg += `   어드민: ${adminTotal.toLocaleString()}원\\n`;');
w('        if (gotganTotal > 0) msg += `   곳간: ${gotganTotal.toLocaleString()}원\\n`;');
w('      }');
w('      await tgSend(msg, chatId);');
w("      log('발송 완료');");
w('    } catch(e) {');
w('      log(`오류: ${e.message}`);');
w('      await tgSend(`❌ 오류: ${e.message}`, chatId);');
w('    } finally {');
w('      busy = false;');
w('    }');
w('    return;');
w('  }');
w('}');
w('');
w('// ── 폴링 ─────────────────────────────────────────────────────────────');
w('let lastUpdateId = 0, polling = false;');
w('const CMDS = [');
w("  '/주문건확인', '주문건확인',");
w("  '/주문출력',   '주문출력',");
w("  '/승인상태',   '승인상태',");
w("  '/명령어리스트','명령어리스트'");
w('];');
w('');
w('async function poll() {');
w('  if (polling) return; polling = true;');
w('  try {');
w('    const updates = await tgGetUpdates(lastUpdateId);');
w('    for (const u of updates) {');
w('      lastUpdateId = u.update_id + 1;');
w('      const msg = u.message || u.edited_message;');
w('      if (!msg?.text) continue;');
w("      const text = msg.text.trim().split(' ')[0];");
w('      const chatId = String(msg.chat.id);');
w('      if (chatId !== TG_CHAT) continue;');
w('      log(`수신: "${text}"`);');
w('      if (CMDS.includes(text)) handleCommand(text, chatId);');
w('    }');
w('  } catch(e) { log(`poll 오류: ${e.message}`); }');
w('  finally { polling = false; }');
w('}');
w('');
w("log('🤖 주문현황 봇 v13');");
w("log('   /주문건확인  /주문출력  /승인상태  /명령어리스트');");
w('setInterval(poll, 3000);');
w('poll();');
w("process.on('SIGINT',  () => { if (fgBrowser) fgBrowser.close(); process.exit(0); });");
w("process.on('SIGTERM', () => { if (fgBrowser) fgBrowser.close(); process.exit(0); });");

// 파일 저장
const content = lines.join('\n');
fs.writeFileSync(TARGET, content, 'utf8');
console.log('✅ tg_status_bot.js v13 작성 완료!');
console.log('   정규식 이중 이스케이프 수정');
console.log('');
console.log('다음 실행:');
console.log('   pm2 restart gotgan-status');
console.log('   pm2 logs gotgan-status --lines 20 --nostream');